apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc2
  labels:
    app: poc2
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc2
      version: v1
  template:
    metadata:
      labels:
        app: poc2
        version: v1
    spec:
      serviceAccountName: poc2
      containers:
        - name: poc2
          image: 'zerotrustpoc/poc2'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: '3000'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: poc2
  labels:
    account: poc2
---
apiVersion: v1
kind: Service
metadata:
  name: poc2
  labels:
    app: poc2
    service: poc2
spec:
  selector:
    app: poc2
  ports:
    - port: 3000
      name: http
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: poc2-destination-rule
spec:
  host: poc2
  trafficPolicy:
    loadBalancer:
      simple: RANDOM
  subsets:
    - name: v1
      labels:
        version: v1
      trafficPolicy:
        loadBalancer:
          simple: ROUND_ROBIN
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: 'poc2-viewer'
  namespace: default
spec:
  selector:
    matchLabels:
      app: poc2
  action: ALLOW
  rules:
    - from:
        - source:
            requestPrincipals: ["seamless/*"]
      to:
        - operation:
            paths: ["/poc2"]
      when:
        - key: request.auth.claims[roles]
          values: ["USER"]
